version: "3.7"
services:
        assembly:
                container_name: assembly_lesson7
                build:
                        context: assembly/.
                        dockerfile: Dockerfile
                volumes:
                        - ./volumes/assembly:/usr/local/tomcat/webapps


