version: "3.7"
services:
        assembly:
                container_name: assembly_lesson7
                build:
                        context: assembly/.
                        dockerfile: Dockerfile
                volumes:
                        - war-storage:/war-storage

        prod:
                container_name: prod_lesson7
                build:
                        context: prod/.
                ports:
                        - "80:8080"
                depends_on:
                        - assembly
                volumes:
                        - war-storage:/usr/local/tomcat/webapps


volumes:
      war-storage:

