---
- name:   install nginx
  hosts:  staging_servers_web
  become: yes

  tasks:
  
  - name: Ensure nginx package is present
    apt:
      name:  nginx
      state: present

  - name: Ensure index.html present in directory
    copy:
      src:  index.html
      dest: /var/www/html

  - name: Ensure nginx package is started
    service:
      name:  nginx
      state: started


- name:   install db
  hosts:  staging_servers_bd
  become: yes

  tasks:
  
 
  - name:  Ensure postgresql package is present 
    apt:
      name:  postgresql
      state: present 


  - name: Ensure postgresql package is started
    service:
     name:  postgresql
     state: started


   

